#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [3]:
import numpy as np

# Create array using numpy
## Create a 1D array
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [4]:
#1D array
arr2=np.array([5,10,15,20,25])
arr2.reshape(1,5) #  row and 5 Columns


array([[ 5, 10, 15, 20, 25]])

In [5]:
# 2D array
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [15]:
print(np.arange(0,10,2))
print(np.arange(0,10,2).reshape(5,1))
print(np.arange(0,10,2).reshape(1,5))

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[[0 2 4 6 8]]


In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Attributes of Numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [20]:
# Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
# Element wise addition
print("Addition: ",arr1+arr2)
# Element wise subtraction
print("Subtraction: ",arr1-arr2)
# Element wise multiplication
print("Multplication: ",arr1*arr2)
# Element wise division
print("Division: ",arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [21]:
# Universal Function
arr=np.array([5,10,15,20,25])
#Square root
print(np.sqrt(arr))
#Exponential 
print(np.exp(arr))
#Sine
print(np.sin(arr))
#Natural Log
print(np.log(arr))


[2.23606798 3.16227766 3.87298335 4.47213595 5.        ]
[1.48413159e+02 2.20264658e+04 3.26901737e+06 4.85165195e+08
 7.20048993e+10]
[-0.95892427 -0.54402111  0.65028784  0.91294525 -0.13235175]
[1.60943791 2.30258509 2.7080502  2.99573227 3.21887582]


In [24]:
# Array slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
print(arr[0][0])
print(arr[0][1])
print(arr[1][0])
print(arr[1:,2:])

1
2
5
[[ 7  8]
 [11 12]]


In [32]:
# Modify array elements
arr[0,0] = 369
print(arr)

[[369   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:]=500
print(arr)

[[369   2   3   4]
 [500 500 500 500]
 [500 500 500 500]]


In [35]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)




Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [37]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])